DROP TABLE IF EXISTS users;

CREATE TABLE users (
    USER_NAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    GOOGLE_ID VARCHAR(255), -- GOOGLE_ID 컬럼 추가
    NAVER_ID VARCHAR(255), -- NAVER_ID 컬럼 추가
    REFRESH_TOKEN  VARCHAR(255),
    USE_YN CHAR(1) NOT NULL,
    -- 로그인 시도 제한 관련 컬럼 추가
    LOGIN_FAILURE_COUNT INT DEFAULT 0,
    LAST_FAILURE_TIMESTAMP TIMESTAMP
);